/*
 * test_unit_fields.h - field ID, index, name, and flag constant tests
 */

#ifndef TEST_UNIT_FIELDS_H
#define TEST_UNIT_FIELDS_H

#include "../src/lsof_fields.h"

TEST(field_ids_are_unique) {
    char ids[] = {
        LSOF_FID_ACCESS, LSOF_FID_CMD, LSOF_FID_FILE_STRUCT_COUNT, LSOF_FID_DEV_CHAR,
        LSOF_FID_DEV_NUM, LSOF_FID_FILE_DESC, LSOF_FID_FILE_STRUCT_ADDR, LSOF_FID_FILE_FLAGS,
        LSOF_FID_INODE, LSOF_FID_NLINK, LSOF_FID_TID, LSOF_FID_LOCK,
        LSOF_FID_LOGIN, LSOF_FID_MARK, LSOF_FID_NAME, LSOF_FID_NODE_ID,
        LSOF_FID_OFFSET, LSOF_FID_PID, LSOF_FID_PGID, LSOF_FID_PROTO,
        LSOF_FID_RDEV, LSOF_FID_PPID, LSOF_FID_SIZE, LSOF_FID_STREAM,
        LSOF_FID_TYPE, LSOF_FID_TCP_TPI_INFO, LSOF_FID_UID, LSOF_FID_ZONE,
        LSOF_FID_SEC_CONTEXT, LSOF_FID_TERM,
    };
    int n = sizeof(ids) / sizeof(ids[0]);
    for (int i = 0; i < n; i++) {
        for (int j = i + 1; j < n; j++) {
            ASSERT_NE(ids[i], ids[j]);
        }
    }
}

TEST(field_indices_sequential) {
    ASSERT_EQ(LSOF_FIX_ACCESS, 0);
    ASSERT_EQ(LSOF_FIX_CMD, 1);
    ASSERT_EQ(LSOF_FIX_FILE_STRUCT_COUNT, 2);
    ASSERT_EQ(LSOF_FIX_DEV_CHAR, 3);
    ASSERT_EQ(LSOF_FIX_DEV_NUM, 4);
    ASSERT_EQ(LSOF_FIX_FILE_DESC, 5);
    ASSERT_EQ(LSOF_FIX_FILE_STRUCT_ADDR, 6);
    ASSERT_EQ(LSOF_FIX_FILE_FLAGS, 7);
    ASSERT_EQ(LSOF_FIX_INODE, 8);
    ASSERT_EQ(LSOF_FIX_NLINK, 9);
    ASSERT_EQ(LSOF_FIX_TID, 10);
    ASSERT_EQ(LSOF_FIX_LOCK, 11);
    ASSERT_EQ(LSOF_FIX_LOGIN, 12);
    ASSERT_EQ(LSOF_FIX_MARK, 13);
    ASSERT_EQ(LSOF_FIX_NAME, 14);
    ASSERT_EQ(LSOF_FIX_NODE_ID, 15);
    ASSERT_EQ(LSOF_FIX_OFFSET, 16);
    ASSERT_EQ(LSOF_FIX_PID, 17);
    ASSERT_EQ(LSOF_FIX_PGID, 18);
    ASSERT_EQ(LSOF_FIX_PROTO, 19);
    ASSERT_EQ(LSOF_FIX_RDEV, 20);
    ASSERT_EQ(LSOF_FIX_PPID, 21);
    ASSERT_EQ(LSOF_FIX_SIZE, 22);
    ASSERT_EQ(LSOF_FIX_STREAM, 23);
    ASSERT_EQ(LSOF_FIX_TYPE, 24);
    ASSERT_EQ(LSOF_FIX_TCP_TPI_INFO, 25);
    ASSERT_EQ(LSOF_FIX_UID, 26);
    ASSERT_EQ(LSOF_FIX_ZONE, 27);
    ASSERT_EQ(LSOF_FIX_SEC_CONTEXT, 28);
    ASSERT_EQ(LSOF_FIX_TERM, 29);
}

TEST(field_id_values) {
    ASSERT_EQ(LSOF_FID_ACCESS, 'a');
    ASSERT_EQ(LSOF_FID_CMD, 'c');
    ASSERT_EQ(LSOF_FID_PID, 'p');
    ASSERT_EQ(LSOF_FID_UID, 'u');
    ASSERT_EQ(LSOF_FID_FILE_DESC, 'f');
    ASSERT_EQ(LSOF_FID_NAME, 'n');
    ASSERT_EQ(LSOF_FID_TYPE, 't');
    ASSERT_EQ(LSOF_FID_SIZE, 's');
    ASSERT_EQ(LSOF_FID_TERM, '0');
}

TEST(field_names_non_null) {
    ASSERT_NOT_NULL(LSOF_FNM_ACCESS);
    ASSERT_NOT_NULL(LSOF_FNM_CMD);
    ASSERT_NOT_NULL(LSOF_FNM_FILE_STRUCT_COUNT);
    ASSERT_NOT_NULL(LSOF_FNM_DEV_CHAR);
    ASSERT_NOT_NULL(LSOF_FNM_DEV_NUM);
    ASSERT_NOT_NULL(LSOF_FNM_FILE_DESC);
    ASSERT_NOT_NULL(LSOF_FNM_FILE_STRUCT_ADDR);
    ASSERT_NOT_NULL(LSOF_FNM_FILE_FLAGS);
    ASSERT_NOT_NULL(LSOF_FNM_INODE);
    ASSERT_NOT_NULL(LSOF_FNM_NLINK);
    ASSERT_NOT_NULL(LSOF_FNM_TID);
    ASSERT_NOT_NULL(LSOF_FNM_LOCK);
    ASSERT_NOT_NULL(LSOF_FNM_LOGIN);
    ASSERT_NOT_NULL(LSOF_FNM_MARK);
    ASSERT_NOT_NULL(LSOF_FNM_NAME);
    ASSERT_NOT_NULL(LSOF_FNM_NODE_ID);
    ASSERT_NOT_NULL(LSOF_FNM_OFFSET);
    ASSERT_NOT_NULL(LSOF_FNM_PID);
    ASSERT_NOT_NULL(LSOF_FNM_PGID);
    ASSERT_NOT_NULL(LSOF_FNM_PROTO);
    ASSERT_NOT_NULL(LSOF_FNM_RDEV);
    ASSERT_NOT_NULL(LSOF_FNM_PPID);
    ASSERT_NOT_NULL(LSOF_FNM_SIZE);
    ASSERT_NOT_NULL(LSOF_FNM_STREAM);
    ASSERT_NOT_NULL(LSOF_FNM_TYPE);
    ASSERT_NOT_NULL(LSOF_FNM_TCP_TPI_INFO);
    ASSERT_NOT_NULL(LSOF_FNM_UID);
    ASSERT_NOT_NULL(LSOF_FNM_ZONE);
    ASSERT_NOT_NULL(LSOF_FNM_SEC_CONTEXT);
    ASSERT_NOT_NULL(LSOF_FNM_TERM);
}

TEST(field_names_non_empty) {
    ASSERT_GT(strlen(LSOF_FNM_ACCESS), 0);
    ASSERT_GT(strlen(LSOF_FNM_CMD), 0);
    ASSERT_GT(strlen(LSOF_FNM_PID), 0);
    ASSERT_GT(strlen(LSOF_FNM_FILE_DESC), 0);
    ASSERT_GT(strlen(LSOF_FNM_NAME), 0);
    ASSERT_GT(strlen(LSOF_FNM_TYPE), 0);
    ASSERT_GT(strlen(LSOF_FNM_SIZE), 0);
    ASSERT_GT(strlen(LSOF_FNM_UID), 0);
}

TEST(field_ids_are_printable_ascii) {
    char ids[] = {
        LSOF_FID_ACCESS, LSOF_FID_CMD, LSOF_FID_FILE_STRUCT_COUNT, LSOF_FID_DEV_CHAR,
        LSOF_FID_DEV_NUM, LSOF_FID_FILE_DESC, LSOF_FID_FILE_STRUCT_ADDR, LSOF_FID_FILE_FLAGS,
        LSOF_FID_INODE, LSOF_FID_NLINK, LSOF_FID_TID, LSOF_FID_LOCK,
        LSOF_FID_LOGIN, LSOF_FID_MARK, LSOF_FID_NAME, LSOF_FID_NODE_ID,
        LSOF_FID_OFFSET, LSOF_FID_PID, LSOF_FID_PGID, LSOF_FID_PROTO,
        LSOF_FID_RDEV, LSOF_FID_PPID, LSOF_FID_SIZE, LSOF_FID_STREAM,
        LSOF_FID_TYPE, LSOF_FID_TCP_TPI_INFO, LSOF_FID_UID, LSOF_FID_ZONE,
        LSOF_FID_SEC_CONTEXT, LSOF_FID_TERM,
    };
    int n = sizeof(ids) / sizeof(ids[0]);
    for (int i = 0; i < n; i++) {
        ASSERT_GE(ids[i], 0x20);
        ASSERT_LT(ids[i], 0x7f);
    }
}

TEST(field_total_count) {
    ASSERT_EQ(LSOF_FIX_TERM, 29);
}


/* ===== Cross-over option value tests ===== */
#define XO_FILESYS  0x1
#define XO_SYMLINK  0x2
#define XO_ALL      (XO_FILESYS | XO_SYMLINK)

TEST(crossover_flags) {
    ASSERT_EQ(XO_FILESYS & XO_SYMLINK, 0);
    ASSERT_EQ(XO_ALL, 0x3);
    ASSERT_TRUE((XO_FILESYS & XO_ALL) != 0);
    ASSERT_TRUE((XO_SYMLINK & XO_ALL) != 0);
}


/* ===== FSV flag tests ===== */
#define FSV_FILE_ADDR 0x1
#define FSV_FILE_COUNT 0x2
#define FSV_FILE_FLAGS 0x4
#define FSV_NODE_ID 0x8

TEST(fsv_flags_no_overlap) {
    ASSERT_EQ(FSV_FILE_ADDR & FSV_FILE_COUNT, 0);
    ASSERT_EQ(FSV_FILE_ADDR & FSV_FILE_FLAGS, 0);
    ASSERT_EQ(FSV_FILE_ADDR & FSV_NODE_ID, 0);
    ASSERT_EQ(FSV_FILE_COUNT & FSV_FILE_FLAGS, 0);
    ASSERT_EQ(FSV_FILE_COUNT & FSV_NODE_ID, 0);
    ASSERT_EQ(FSV_FILE_FLAGS & FSV_NODE_ID, 0);
}

TEST(fsv_flags_combine) {
    int all = FSV_FILE_ADDR | FSV_FILE_COUNT | FSV_FILE_FLAGS | FSV_NODE_ID;
    ASSERT_EQ(all, 0xf);
    ASSERT_TRUE((all & FSV_FILE_ADDR) != 0);
    ASSERT_TRUE((all & FSV_FILE_COUNT) != 0);
    ASSERT_TRUE((all & FSV_FILE_FLAGS) != 0);
    ASSERT_TRUE((all & FSV_NODE_ID) != 0);
}

#endif /* TEST_UNIT_FIELDS_H */
