# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wizard/forkedRepos/lsof

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wizard/forkedRepos/lsof

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wizard/forkedRepos/lsof/CMakeFiles /Users/wizard/forkedRepos/lsof//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wizard/forkedRepos/lsof/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lsof

# Build rule for target.
lsof: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lsof
.PHONY : lsof

# fast build rule for target.
lsof/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/build
.PHONY : lsof/fast

src/arg.o: src/arg.c.o
.PHONY : src/arg.o

# target to build an object file
src/arg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/arg.c.o
.PHONY : src/arg.c.o

src/arg.i: src/arg.c.i
.PHONY : src/arg.i

# target to preprocess a source file
src/arg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/arg.c.i
.PHONY : src/arg.c.i

src/arg.s: src/arg.c.s
.PHONY : src/arg.s

# target to generate assembly for a file
src/arg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/arg.c.s
.PHONY : src/arg.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/main.c.s
.PHONY : src/main.c.s

src/misc.o: src/misc.c.o
.PHONY : src/misc.o

# target to build an object file
src/misc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/misc.c.o
.PHONY : src/misc.c.o

src/misc.i: src/misc.c.i
.PHONY : src/misc.i

# target to preprocess a source file
src/misc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/misc.c.i
.PHONY : src/misc.c.i

src/misc.s: src/misc.c.s
.PHONY : src/misc.s

# target to generate assembly for a file
src/misc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/misc.c.s
.PHONY : src/misc.c.s

src/node.o: src/node.c.o
.PHONY : src/node.o

# target to build an object file
src/node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/node.c.o
.PHONY : src/node.c.o

src/node.i: src/node.c.i
.PHONY : src/node.i

# target to preprocess a source file
src/node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/node.c.i
.PHONY : src/node.c.i

src/node.s: src/node.c.s
.PHONY : src/node.s

# target to generate assembly for a file
src/node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/node.c.s
.PHONY : src/node.c.s

src/print.o: src/print.c.o
.PHONY : src/print.o

# target to build an object file
src/print.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/print.c.o
.PHONY : src/print.c.o

src/print.i: src/print.c.i
.PHONY : src/print.i

# target to preprocess a source file
src/print.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/print.c.i
.PHONY : src/print.c.i

src/print.s: src/print.c.s
.PHONY : src/print.s

# target to generate assembly for a file
src/print.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/print.c.s
.PHONY : src/print.c.s

src/proc.o: src/proc.c.o
.PHONY : src/proc.o

# target to build an object file
src/proc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/proc.c.o
.PHONY : src/proc.c.o

src/proc.i: src/proc.c.i
.PHONY : src/proc.i

# target to preprocess a source file
src/proc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/proc.c.i
.PHONY : src/proc.c.i

src/proc.s: src/proc.c.s
.PHONY : src/proc.s

# target to generate assembly for a file
src/proc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/proc.c.s
.PHONY : src/proc.c.s

src/store.o: src/store.c.o
.PHONY : src/store.o

# target to build an object file
src/store.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/store.c.o
.PHONY : src/store.c.o

src/store.i: src/store.c.i
.PHONY : src/store.i

# target to preprocess a source file
src/store.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/store.c.i
.PHONY : src/store.c.i

src/store.s: src/store.c.s
.PHONY : src/store.s

# target to generate assembly for a file
src/store.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/store.c.s
.PHONY : src/store.c.s

src/usage.o: src/usage.c.o
.PHONY : src/usage.o

# target to build an object file
src/usage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/usage.c.o
.PHONY : src/usage.c.o

src/usage.i: src/usage.c.i
.PHONY : src/usage.i

# target to preprocess a source file
src/usage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/usage.c.i
.PHONY : src/usage.c.i

src/usage.s: src/usage.c.s
.PHONY : src/usage.s

# target to generate assembly for a file
src/usage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/usage.c.s
.PHONY : src/usage.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lsof"
	@echo "... src/arg.o"
	@echo "... src/arg.i"
	@echo "... src/arg.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/misc.o"
	@echo "... src/misc.i"
	@echo "... src/misc.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/print.o"
	@echo "... src/print.i"
	@echo "... src/print.s"
	@echo "... src/proc.o"
	@echo "... src/proc.i"
	@echo "... src/proc.s"
	@echo "... src/store.o"
	@echo "... src/store.i"
	@echo "... src/store.s"
	@echo "... src/usage.o"
	@echo "... src/usage.i"
	@echo "... src/usage.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

