# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wizard/forkedRepos/lsof

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wizard/forkedRepos/lsof

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wizard/forkedRepos/lsof/CMakeFiles /Users/wizard/forkedRepos/lsof//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wizard/forkedRepos/lsof/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lsof

# Build rule for target.
lsof: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lsof
.PHONY : lsof

# fast build rule for target.
lsof/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/build
.PHONY : lsof/fast

#=============================================================================
# Target rules for targets named test_unit

# Build rule for target.
test_unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unit
.PHONY : test_unit

# fast build rule for target.
test_unit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_unit.dir/build.make CMakeFiles/test_unit.dir/build
.PHONY : test_unit/fast

#=============================================================================
# Target rules for targets named test_integration

# Build rule for target.
test_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration
.PHONY : test_integration

# fast build rule for target.
test_integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integration.dir/build.make CMakeFiles/test_integration.dir/build
.PHONY : test_integration/fast

#=============================================================================
# Target rules for targets named bench_core

# Build rule for target.
bench_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_core
.PHONY : bench_core

# fast build rule for target.
bench_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_core.dir/build.make CMakeFiles/bench_core.dir/build
.PHONY : bench_core/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named run_benchmarks

# Build rule for target.
run_benchmarks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_benchmarks
.PHONY : run_benchmarks

# fast build rule for target.
run_benchmarks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_benchmarks.dir/build.make CMakeFiles/run_benchmarks.dir/build
.PHONY : run_benchmarks/fast

bench/bench_core.o: bench/bench_core.c.o
.PHONY : bench/bench_core.o

# target to build an object file
bench/bench_core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_core.dir/build.make CMakeFiles/bench_core.dir/bench/bench_core.c.o
.PHONY : bench/bench_core.c.o

bench/bench_core.i: bench/bench_core.c.i
.PHONY : bench/bench_core.i

# target to preprocess a source file
bench/bench_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_core.dir/build.make CMakeFiles/bench_core.dir/bench/bench_core.c.i
.PHONY : bench/bench_core.c.i

bench/bench_core.s: bench/bench_core.c.s
.PHONY : bench/bench_core.s

# target to generate assembly for a file
bench/bench_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_core.dir/build.make CMakeFiles/bench_core.dir/bench/bench_core.c.s
.PHONY : bench/bench_core.c.s

src/arg.o: src/arg.c.o
.PHONY : src/arg.o

# target to build an object file
src/arg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/arg.c.o
.PHONY : src/arg.c.o

src/arg.i: src/arg.c.i
.PHONY : src/arg.i

# target to preprocess a source file
src/arg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/arg.c.i
.PHONY : src/arg.c.i

src/arg.s: src/arg.c.s
.PHONY : src/arg.s

# target to generate assembly for a file
src/arg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/arg.c.s
.PHONY : src/arg.c.s

src/dialects/darwin/libproc/ddev.o: src/dialects/darwin/libproc/ddev.c.o
.PHONY : src/dialects/darwin/libproc/ddev.o

# target to build an object file
src/dialects/darwin/libproc/ddev.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/ddev.c.o
.PHONY : src/dialects/darwin/libproc/ddev.c.o

src/dialects/darwin/libproc/ddev.i: src/dialects/darwin/libproc/ddev.c.i
.PHONY : src/dialects/darwin/libproc/ddev.i

# target to preprocess a source file
src/dialects/darwin/libproc/ddev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/ddev.c.i
.PHONY : src/dialects/darwin/libproc/ddev.c.i

src/dialects/darwin/libproc/ddev.s: src/dialects/darwin/libproc/ddev.c.s
.PHONY : src/dialects/darwin/libproc/ddev.s

# target to generate assembly for a file
src/dialects/darwin/libproc/ddev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/ddev.c.s
.PHONY : src/dialects/darwin/libproc/ddev.c.s

src/dialects/darwin/libproc/dfile.o: src/dialects/darwin/libproc/dfile.c.o
.PHONY : src/dialects/darwin/libproc/dfile.o

# target to build an object file
src/dialects/darwin/libproc/dfile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dfile.c.o
.PHONY : src/dialects/darwin/libproc/dfile.c.o

src/dialects/darwin/libproc/dfile.i: src/dialects/darwin/libproc/dfile.c.i
.PHONY : src/dialects/darwin/libproc/dfile.i

# target to preprocess a source file
src/dialects/darwin/libproc/dfile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dfile.c.i
.PHONY : src/dialects/darwin/libproc/dfile.c.i

src/dialects/darwin/libproc/dfile.s: src/dialects/darwin/libproc/dfile.c.s
.PHONY : src/dialects/darwin/libproc/dfile.s

# target to generate assembly for a file
src/dialects/darwin/libproc/dfile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dfile.c.s
.PHONY : src/dialects/darwin/libproc/dfile.c.s

src/dialects/darwin/libproc/dmnt.o: src/dialects/darwin/libproc/dmnt.c.o
.PHONY : src/dialects/darwin/libproc/dmnt.o

# target to build an object file
src/dialects/darwin/libproc/dmnt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dmnt.c.o
.PHONY : src/dialects/darwin/libproc/dmnt.c.o

src/dialects/darwin/libproc/dmnt.i: src/dialects/darwin/libproc/dmnt.c.i
.PHONY : src/dialects/darwin/libproc/dmnt.i

# target to preprocess a source file
src/dialects/darwin/libproc/dmnt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dmnt.c.i
.PHONY : src/dialects/darwin/libproc/dmnt.c.i

src/dialects/darwin/libproc/dmnt.s: src/dialects/darwin/libproc/dmnt.c.s
.PHONY : src/dialects/darwin/libproc/dmnt.s

# target to generate assembly for a file
src/dialects/darwin/libproc/dmnt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dmnt.c.s
.PHONY : src/dialects/darwin/libproc/dmnt.c.s

src/dialects/darwin/libproc/dproc.o: src/dialects/darwin/libproc/dproc.c.o
.PHONY : src/dialects/darwin/libproc/dproc.o

# target to build an object file
src/dialects/darwin/libproc/dproc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dproc.c.o
.PHONY : src/dialects/darwin/libproc/dproc.c.o

src/dialects/darwin/libproc/dproc.i: src/dialects/darwin/libproc/dproc.c.i
.PHONY : src/dialects/darwin/libproc/dproc.i

# target to preprocess a source file
src/dialects/darwin/libproc/dproc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dproc.c.i
.PHONY : src/dialects/darwin/libproc/dproc.c.i

src/dialects/darwin/libproc/dproc.s: src/dialects/darwin/libproc/dproc.c.s
.PHONY : src/dialects/darwin/libproc/dproc.s

# target to generate assembly for a file
src/dialects/darwin/libproc/dproc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dproc.c.s
.PHONY : src/dialects/darwin/libproc/dproc.c.s

src/dialects/darwin/libproc/dsock.o: src/dialects/darwin/libproc/dsock.c.o
.PHONY : src/dialects/darwin/libproc/dsock.o

# target to build an object file
src/dialects/darwin/libproc/dsock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dsock.c.o
.PHONY : src/dialects/darwin/libproc/dsock.c.o

src/dialects/darwin/libproc/dsock.i: src/dialects/darwin/libproc/dsock.c.i
.PHONY : src/dialects/darwin/libproc/dsock.i

# target to preprocess a source file
src/dialects/darwin/libproc/dsock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dsock.c.i
.PHONY : src/dialects/darwin/libproc/dsock.c.i

src/dialects/darwin/libproc/dsock.s: src/dialects/darwin/libproc/dsock.c.s
.PHONY : src/dialects/darwin/libproc/dsock.s

# target to generate assembly for a file
src/dialects/darwin/libproc/dsock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dsock.c.s
.PHONY : src/dialects/darwin/libproc/dsock.c.s

src/dialects/darwin/libproc/dstore.o: src/dialects/darwin/libproc/dstore.c.o
.PHONY : src/dialects/darwin/libproc/dstore.o

# target to build an object file
src/dialects/darwin/libproc/dstore.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dstore.c.o
.PHONY : src/dialects/darwin/libproc/dstore.c.o

src/dialects/darwin/libproc/dstore.i: src/dialects/darwin/libproc/dstore.c.i
.PHONY : src/dialects/darwin/libproc/dstore.i

# target to preprocess a source file
src/dialects/darwin/libproc/dstore.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dstore.c.i
.PHONY : src/dialects/darwin/libproc/dstore.c.i

src/dialects/darwin/libproc/dstore.s: src/dialects/darwin/libproc/dstore.c.s
.PHONY : src/dialects/darwin/libproc/dstore.s

# target to generate assembly for a file
src/dialects/darwin/libproc/dstore.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/dialects/darwin/libproc/dstore.c.s
.PHONY : src/dialects/darwin/libproc/dstore.c.s

src/lib/ckkv.o: src/lib/ckkv.c.o
.PHONY : src/lib/ckkv.o

# target to build an object file
src/lib/ckkv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/ckkv.c.o
.PHONY : src/lib/ckkv.c.o

src/lib/ckkv.i: src/lib/ckkv.c.i
.PHONY : src/lib/ckkv.i

# target to preprocess a source file
src/lib/ckkv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/ckkv.c.i
.PHONY : src/lib/ckkv.c.i

src/lib/ckkv.s: src/lib/ckkv.c.s
.PHONY : src/lib/ckkv.s

# target to generate assembly for a file
src/lib/ckkv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/ckkv.c.s
.PHONY : src/lib/ckkv.c.s

src/lib/cvfs.o: src/lib/cvfs.c.o
.PHONY : src/lib/cvfs.o

# target to build an object file
src/lib/cvfs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/cvfs.c.o
.PHONY : src/lib/cvfs.c.o

src/lib/cvfs.i: src/lib/cvfs.c.i
.PHONY : src/lib/cvfs.i

# target to preprocess a source file
src/lib/cvfs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/cvfs.c.i
.PHONY : src/lib/cvfs.c.i

src/lib/cvfs.s: src/lib/cvfs.c.s
.PHONY : src/lib/cvfs.s

# target to generate assembly for a file
src/lib/cvfs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/cvfs.c.s
.PHONY : src/lib/cvfs.c.s

src/lib/dvch.o: src/lib/dvch.c.o
.PHONY : src/lib/dvch.o

# target to build an object file
src/lib/dvch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/dvch.c.o
.PHONY : src/lib/dvch.c.o

src/lib/dvch.i: src/lib/dvch.c.i
.PHONY : src/lib/dvch.i

# target to preprocess a source file
src/lib/dvch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/dvch.c.i
.PHONY : src/lib/dvch.c.i

src/lib/dvch.s: src/lib/dvch.c.s
.PHONY : src/lib/dvch.s

# target to generate assembly for a file
src/lib/dvch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/dvch.c.s
.PHONY : src/lib/dvch.c.s

src/lib/fino.o: src/lib/fino.c.o
.PHONY : src/lib/fino.o

# target to build an object file
src/lib/fino.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/fino.c.o
.PHONY : src/lib/fino.c.o

src/lib/fino.i: src/lib/fino.c.i
.PHONY : src/lib/fino.i

# target to preprocess a source file
src/lib/fino.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/fino.c.i
.PHONY : src/lib/fino.c.i

src/lib/fino.s: src/lib/fino.c.s
.PHONY : src/lib/fino.s

# target to generate assembly for a file
src/lib/fino.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/fino.c.s
.PHONY : src/lib/fino.c.s

src/lib/isfn.o: src/lib/isfn.c.o
.PHONY : src/lib/isfn.o

# target to build an object file
src/lib/isfn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/isfn.c.o
.PHONY : src/lib/isfn.c.o

src/lib/isfn.i: src/lib/isfn.c.i
.PHONY : src/lib/isfn.i

# target to preprocess a source file
src/lib/isfn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/isfn.c.i
.PHONY : src/lib/isfn.c.i

src/lib/isfn.s: src/lib/isfn.c.s
.PHONY : src/lib/isfn.s

# target to generate assembly for a file
src/lib/isfn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/isfn.c.s
.PHONY : src/lib/isfn.c.s

src/lib/lkud.o: src/lib/lkud.c.o
.PHONY : src/lib/lkud.o

# target to build an object file
src/lib/lkud.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/lkud.c.o
.PHONY : src/lib/lkud.c.o

src/lib/lkud.i: src/lib/lkud.c.i
.PHONY : src/lib/lkud.i

# target to preprocess a source file
src/lib/lkud.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/lkud.c.i
.PHONY : src/lib/lkud.c.i

src/lib/lkud.s: src/lib/lkud.c.s
.PHONY : src/lib/lkud.s

# target to generate assembly for a file
src/lib/lkud.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/lkud.c.s
.PHONY : src/lib/lkud.c.s

src/lib/pdvn.o: src/lib/pdvn.c.o
.PHONY : src/lib/pdvn.o

# target to build an object file
src/lib/pdvn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/pdvn.c.o
.PHONY : src/lib/pdvn.c.o

src/lib/pdvn.i: src/lib/pdvn.c.i
.PHONY : src/lib/pdvn.i

# target to preprocess a source file
src/lib/pdvn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/pdvn.c.i
.PHONY : src/lib/pdvn.c.i

src/lib/pdvn.s: src/lib/pdvn.c.s
.PHONY : src/lib/pdvn.s

# target to generate assembly for a file
src/lib/pdvn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/pdvn.c.s
.PHONY : src/lib/pdvn.c.s

src/lib/prfp.o: src/lib/prfp.c.o
.PHONY : src/lib/prfp.o

# target to build an object file
src/lib/prfp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/prfp.c.o
.PHONY : src/lib/prfp.c.o

src/lib/prfp.i: src/lib/prfp.c.i
.PHONY : src/lib/prfp.i

# target to preprocess a source file
src/lib/prfp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/prfp.c.i
.PHONY : src/lib/prfp.c.i

src/lib/prfp.s: src/lib/prfp.c.s
.PHONY : src/lib/prfp.s

# target to generate assembly for a file
src/lib/prfp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/prfp.c.s
.PHONY : src/lib/prfp.c.s

src/lib/ptti.o: src/lib/ptti.c.o
.PHONY : src/lib/ptti.o

# target to build an object file
src/lib/ptti.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/ptti.c.o
.PHONY : src/lib/ptti.c.o

src/lib/ptti.i: src/lib/ptti.c.i
.PHONY : src/lib/ptti.i

# target to preprocess a source file
src/lib/ptti.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/ptti.c.i
.PHONY : src/lib/ptti.c.i

src/lib/ptti.s: src/lib/ptti.c.s
.PHONY : src/lib/ptti.s

# target to generate assembly for a file
src/lib/ptti.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/ptti.c.s
.PHONY : src/lib/ptti.c.s

src/lib/rdev.o: src/lib/rdev.c.o
.PHONY : src/lib/rdev.o

# target to build an object file
src/lib/rdev.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rdev.c.o
.PHONY : src/lib/rdev.c.o

src/lib/rdev.i: src/lib/rdev.c.i
.PHONY : src/lib/rdev.i

# target to preprocess a source file
src/lib/rdev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rdev.c.i
.PHONY : src/lib/rdev.c.i

src/lib/rdev.s: src/lib/rdev.c.s
.PHONY : src/lib/rdev.s

# target to generate assembly for a file
src/lib/rdev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rdev.c.s
.PHONY : src/lib/rdev.c.s

src/lib/regex.o: src/lib/regex.c.o
.PHONY : src/lib/regex.o

# target to build an object file
src/lib/regex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/regex.c.o
.PHONY : src/lib/regex.c.o

src/lib/regex.i: src/lib/regex.c.i
.PHONY : src/lib/regex.i

# target to preprocess a source file
src/lib/regex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/regex.c.i
.PHONY : src/lib/regex.c.i

src/lib/regex.s: src/lib/regex.c.s
.PHONY : src/lib/regex.s

# target to generate assembly for a file
src/lib/regex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/regex.c.s
.PHONY : src/lib/regex.c.s

src/lib/rmnt.o: src/lib/rmnt.c.o
.PHONY : src/lib/rmnt.o

# target to build an object file
src/lib/rmnt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rmnt.c.o
.PHONY : src/lib/rmnt.c.o

src/lib/rmnt.i: src/lib/rmnt.c.i
.PHONY : src/lib/rmnt.i

# target to preprocess a source file
src/lib/rmnt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rmnt.c.i
.PHONY : src/lib/rmnt.c.i

src/lib/rmnt.s: src/lib/rmnt.c.s
.PHONY : src/lib/rmnt.s

# target to generate assembly for a file
src/lib/rmnt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rmnt.c.s
.PHONY : src/lib/rmnt.c.s

src/lib/rnam.o: src/lib/rnam.c.o
.PHONY : src/lib/rnam.o

# target to build an object file
src/lib/rnam.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnam.c.o
.PHONY : src/lib/rnam.c.o

src/lib/rnam.i: src/lib/rnam.c.i
.PHONY : src/lib/rnam.i

# target to preprocess a source file
src/lib/rnam.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnam.c.i
.PHONY : src/lib/rnam.c.i

src/lib/rnam.s: src/lib/rnam.c.s
.PHONY : src/lib/rnam.s

# target to generate assembly for a file
src/lib/rnam.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnam.c.s
.PHONY : src/lib/rnam.c.s

src/lib/rnch.o: src/lib/rnch.c.o
.PHONY : src/lib/rnch.o

# target to build an object file
src/lib/rnch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnch.c.o
.PHONY : src/lib/rnch.c.o

src/lib/rnch.i: src/lib/rnch.c.i
.PHONY : src/lib/rnch.i

# target to preprocess a source file
src/lib/rnch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnch.c.i
.PHONY : src/lib/rnch.c.i

src/lib/rnch.s: src/lib/rnch.c.s
.PHONY : src/lib/rnch.s

# target to generate assembly for a file
src/lib/rnch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnch.c.s
.PHONY : src/lib/rnch.c.s

src/lib/rnmh.o: src/lib/rnmh.c.o
.PHONY : src/lib/rnmh.o

# target to build an object file
src/lib/rnmh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnmh.c.o
.PHONY : src/lib/rnmh.c.o

src/lib/rnmh.i: src/lib/rnmh.c.i
.PHONY : src/lib/rnmh.i

# target to preprocess a source file
src/lib/rnmh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnmh.c.i
.PHONY : src/lib/rnmh.c.i

src/lib/rnmh.s: src/lib/rnmh.c.s
.PHONY : src/lib/rnmh.s

# target to generate assembly for a file
src/lib/rnmh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/rnmh.c.s
.PHONY : src/lib/rnmh.c.s

src/lib/snpf.o: src/lib/snpf.c.o
.PHONY : src/lib/snpf.o

# target to build an object file
src/lib/snpf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/snpf.c.o
.PHONY : src/lib/snpf.c.o

src/lib/snpf.i: src/lib/snpf.c.i
.PHONY : src/lib/snpf.i

# target to preprocess a source file
src/lib/snpf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/snpf.c.i
.PHONY : src/lib/snpf.c.i

src/lib/snpf.s: src/lib/snpf.c.s
.PHONY : src/lib/snpf.s

# target to generate assembly for a file
src/lib/snpf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/lib/snpf.c.s
.PHONY : src/lib/snpf.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/main.c.s
.PHONY : src/main.c.s

src/misc.o: src/misc.c.o
.PHONY : src/misc.o

# target to build an object file
src/misc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/misc.c.o
.PHONY : src/misc.c.o

src/misc.i: src/misc.c.i
.PHONY : src/misc.i

# target to preprocess a source file
src/misc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/misc.c.i
.PHONY : src/misc.c.i

src/misc.s: src/misc.c.s
.PHONY : src/misc.s

# target to generate assembly for a file
src/misc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/misc.c.s
.PHONY : src/misc.c.s

src/node.o: src/node.c.o
.PHONY : src/node.o

# target to build an object file
src/node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/node.c.o
.PHONY : src/node.c.o

src/node.i: src/node.c.i
.PHONY : src/node.i

# target to preprocess a source file
src/node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/node.c.i
.PHONY : src/node.c.i

src/node.s: src/node.c.s
.PHONY : src/node.s

# target to generate assembly for a file
src/node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/node.c.s
.PHONY : src/node.c.s

src/print.o: src/print.c.o
.PHONY : src/print.o

# target to build an object file
src/print.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/print.c.o
.PHONY : src/print.c.o

src/print.i: src/print.c.i
.PHONY : src/print.i

# target to preprocess a source file
src/print.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/print.c.i
.PHONY : src/print.c.i

src/print.s: src/print.c.s
.PHONY : src/print.s

# target to generate assembly for a file
src/print.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/print.c.s
.PHONY : src/print.c.s

src/proc.o: src/proc.c.o
.PHONY : src/proc.o

# target to build an object file
src/proc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/proc.c.o
.PHONY : src/proc.c.o

src/proc.i: src/proc.c.i
.PHONY : src/proc.i

# target to preprocess a source file
src/proc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/proc.c.i
.PHONY : src/proc.c.i

src/proc.s: src/proc.c.s
.PHONY : src/proc.s

# target to generate assembly for a file
src/proc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/proc.c.s
.PHONY : src/proc.c.s

src/store.o: src/store.c.o
.PHONY : src/store.o

# target to build an object file
src/store.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/store.c.o
.PHONY : src/store.c.o

src/store.i: src/store.c.i
.PHONY : src/store.i

# target to preprocess a source file
src/store.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/store.c.i
.PHONY : src/store.c.i

src/store.s: src/store.c.s
.PHONY : src/store.s

# target to generate assembly for a file
src/store.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/store.c.s
.PHONY : src/store.c.s

src/usage.o: src/usage.c.o
.PHONY : src/usage.o

# target to build an object file
src/usage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/usage.c.o
.PHONY : src/usage.c.o

src/usage.i: src/usage.c.i
.PHONY : src/usage.i

# target to preprocess a source file
src/usage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/usage.c.i
.PHONY : src/usage.c.i

src/usage.s: src/usage.c.s
.PHONY : src/usage.s

# target to generate assembly for a file
src/usage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/usage.c.s
.PHONY : src/usage.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsof.dir/build.make CMakeFiles/lsof.dir/src/util.c.s
.PHONY : src/util.c.s

test/test_integration.o: test/test_integration.c.o
.PHONY : test/test_integration.o

# target to build an object file
test/test_integration.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integration.dir/build.make CMakeFiles/test_integration.dir/test/test_integration.c.o
.PHONY : test/test_integration.c.o

test/test_integration.i: test/test_integration.c.i
.PHONY : test/test_integration.i

# target to preprocess a source file
test/test_integration.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integration.dir/build.make CMakeFiles/test_integration.dir/test/test_integration.c.i
.PHONY : test/test_integration.c.i

test/test_integration.s: test/test_integration.c.s
.PHONY : test/test_integration.s

# target to generate assembly for a file
test/test_integration.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integration.dir/build.make CMakeFiles/test_integration.dir/test/test_integration.c.s
.PHONY : test/test_integration.c.s

test/test_unit.o: test/test_unit.c.o
.PHONY : test/test_unit.o

# target to build an object file
test/test_unit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_unit.dir/build.make CMakeFiles/test_unit.dir/test/test_unit.c.o
.PHONY : test/test_unit.c.o

test/test_unit.i: test/test_unit.c.i
.PHONY : test/test_unit.i

# target to preprocess a source file
test/test_unit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_unit.dir/build.make CMakeFiles/test_unit.dir/test/test_unit.c.i
.PHONY : test/test_unit.c.i

test/test_unit.s: test/test_unit.c.s
.PHONY : test/test_unit.s

# target to generate assembly for a file
test/test_unit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_unit.dir/build.make CMakeFiles/test_unit.dir/test/test_unit.c.s
.PHONY : test/test_unit.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... run_benchmarks"
	@echo "... run_tests"
	@echo "... bench_core"
	@echo "... lsof"
	@echo "... test_integration"
	@echo "... test_unit"
	@echo "... bench/bench_core.o"
	@echo "... bench/bench_core.i"
	@echo "... bench/bench_core.s"
	@echo "... src/arg.o"
	@echo "... src/arg.i"
	@echo "... src/arg.s"
	@echo "... src/dialects/darwin/libproc/ddev.o"
	@echo "... src/dialects/darwin/libproc/ddev.i"
	@echo "... src/dialects/darwin/libproc/ddev.s"
	@echo "... src/dialects/darwin/libproc/dfile.o"
	@echo "... src/dialects/darwin/libproc/dfile.i"
	@echo "... src/dialects/darwin/libproc/dfile.s"
	@echo "... src/dialects/darwin/libproc/dmnt.o"
	@echo "... src/dialects/darwin/libproc/dmnt.i"
	@echo "... src/dialects/darwin/libproc/dmnt.s"
	@echo "... src/dialects/darwin/libproc/dproc.o"
	@echo "... src/dialects/darwin/libproc/dproc.i"
	@echo "... src/dialects/darwin/libproc/dproc.s"
	@echo "... src/dialects/darwin/libproc/dsock.o"
	@echo "... src/dialects/darwin/libproc/dsock.i"
	@echo "... src/dialects/darwin/libproc/dsock.s"
	@echo "... src/dialects/darwin/libproc/dstore.o"
	@echo "... src/dialects/darwin/libproc/dstore.i"
	@echo "... src/dialects/darwin/libproc/dstore.s"
	@echo "... src/lib/ckkv.o"
	@echo "... src/lib/ckkv.i"
	@echo "... src/lib/ckkv.s"
	@echo "... src/lib/cvfs.o"
	@echo "... src/lib/cvfs.i"
	@echo "... src/lib/cvfs.s"
	@echo "... src/lib/dvch.o"
	@echo "... src/lib/dvch.i"
	@echo "... src/lib/dvch.s"
	@echo "... src/lib/fino.o"
	@echo "... src/lib/fino.i"
	@echo "... src/lib/fino.s"
	@echo "... src/lib/isfn.o"
	@echo "... src/lib/isfn.i"
	@echo "... src/lib/isfn.s"
	@echo "... src/lib/lkud.o"
	@echo "... src/lib/lkud.i"
	@echo "... src/lib/lkud.s"
	@echo "... src/lib/pdvn.o"
	@echo "... src/lib/pdvn.i"
	@echo "... src/lib/pdvn.s"
	@echo "... src/lib/prfp.o"
	@echo "... src/lib/prfp.i"
	@echo "... src/lib/prfp.s"
	@echo "... src/lib/ptti.o"
	@echo "... src/lib/ptti.i"
	@echo "... src/lib/ptti.s"
	@echo "... src/lib/rdev.o"
	@echo "... src/lib/rdev.i"
	@echo "... src/lib/rdev.s"
	@echo "... src/lib/regex.o"
	@echo "... src/lib/regex.i"
	@echo "... src/lib/regex.s"
	@echo "... src/lib/rmnt.o"
	@echo "... src/lib/rmnt.i"
	@echo "... src/lib/rmnt.s"
	@echo "... src/lib/rnam.o"
	@echo "... src/lib/rnam.i"
	@echo "... src/lib/rnam.s"
	@echo "... src/lib/rnch.o"
	@echo "... src/lib/rnch.i"
	@echo "... src/lib/rnch.s"
	@echo "... src/lib/rnmh.o"
	@echo "... src/lib/rnmh.i"
	@echo "... src/lib/rnmh.s"
	@echo "... src/lib/snpf.o"
	@echo "... src/lib/snpf.i"
	@echo "... src/lib/snpf.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/misc.o"
	@echo "... src/misc.i"
	@echo "... src/misc.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/print.o"
	@echo "... src/print.i"
	@echo "... src/print.s"
	@echo "... src/proc.o"
	@echo "... src/proc.i"
	@echo "... src/proc.s"
	@echo "... src/store.o"
	@echo "... src/store.i"
	@echo "... src/store.s"
	@echo "... src/usage.o"
	@echo "... src/usage.i"
	@echo "... src/usage.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... test/test_integration.o"
	@echo "... test/test_integration.i"
	@echo "... test/test_integration.s"
	@echo "... test/test_unit.o"
	@echo "... test/test_unit.i"
	@echo "... test/test_unit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

